export const DataFeed = [
  {
    id: '61baf6f75f694f7c7b6c85ba',
    connectomeId: 'ALL_20211213',
    docType: null,
    docId: 'ds-investing-eng-N8673787028760657737-0-0',
    dataSize: '2x2',
    dataTemplate: 'chart',
    topicSims: [
      {
        topic: 'Financial_technology',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Companies_based_in_San_Francisco',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Companies_in_the_NASDAQ-100',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Video_game_development_companies',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Companies_in_the_PRISM_network',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Elon_Musk',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Deep_learning',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Artificial_intelligence',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'American_technology_company_founders',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Computing_and_society',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Windows_games',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'New_media',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Video_game_terminology',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Battery_electric_vehicle_manufacturers',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Virtual_reality',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Car_brands',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Promotion_and_marketing_communications',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Open-world_video_games',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Augmented_reality',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Internet_of_things',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Technology_in_society',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Occupational_safety_and_health',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Renewable_energy',
        w2vSim: null,
        asaSim: null,
      },
      {
        topic: 'Group_of_Eight_nations',
        w2vSim: null,
        asaSim: null,
      },
    ],
    w2vSim: null,
    gmuseSim: null,
    score: 0.7668511160075318,
    esaSim: null,
    topic: 'Financial_technology',
    sourceId: 'https://www.investing.com/news/stock-market-news/stablecoins-steal-the-limelight-from-subdued-bitcoin-2709494',
    commentId: '',
    replyId: '',
    publishedAt: {
      seconds: 1639409568,
      nanos: 0,
    },
    projectIds: ['deepsignal_investor_public'],
    webSourceId: 'kospi_news_en',
    webSourceCategory: ['FINANCE'],
    collectedAt: {
      seconds: 1639477968,
      nanos: 0,
    },
    serviceType: 'INVESTING',
    sourceUri: null,
    title: 'Stablecoins steal the limelight from subdued bitcoin',
    content:
      "© Reuters. FILE PHOTO: Representation of cryptocurrency bitcoin is seen in this illustration taken November 29, 2021. REUTERS/Dado Ruvic/Illustration/File Photo By Lisa Pauline Mattackal and Vidya Ranganathan (Reuters) - As bitcoin, the world's largest cryptocurrency, struggles to recover after a massive crash, regulatory and private sector focus has turned to another part of the digital currency world: stablecoins. The past week saw Meta Platforms Inc pilot its stablecoin payments wallet, while the world's largest payments processor Visa (NYSE:V) launched a crypto advisory service and said stablecoins, might become the medium of exchange rather than cryptocurrencies. Stablecoins are a form a virtual currency with values pegged to traditional assets such as the U.S. dollar or commodities, and their rise has accelerated discussion by central banks across the world about digital versions of their currencies. Analysts at digital platform Alkemi Network were among those who hailed Visa's move as evidence that the cryptocurrency and decentralised finance ecosystem is moving towards maturity. \"Making a visible attempt to play by traditional finance rules is definitely gathering momentum as a movement within the crypto ecosystem,\" they wrote. Japan's financial regulator said last week it will come up with rules in 2022 to restrict the issuance of stablecoins to banks and wire transfer firms. In the United States, even as top executives from major cryptocurrency companies including Coinbase (NASDAQ:COIN) and Circle urged Congress to provide clearer bespoke rules for the industry, Treasury Secretary Janet Yellen and a group of bank chief executives discussed the need to regulate stablecoins. Meta's cryptocurrency wallet, Novi, will allow users to send and receive money through the social media giant's messaging app WhatsApp and will use a stablecoin named Pax Dollar. Research platform Delphi Digital says stablecoins have grown substantially in the past month, with the market capitalisation of the top five stablecoins swelling to nearly $150 billion from $129 billion. Tether, the largest stablecoin, has a market value of $76 billion. Meanwhile, the central banks of Switzerland and France claimed success in Europe's first cross-border trial of central bank digital currency (CBDC) payments, after testing project Jura, named after the mountains between the two countries. BARGAIN HUNTERS With bitcoin capped at $50,000 for most of the week since its flash crash on Dec. 4, the market capitalisation of the 15,541 coins on the CoinMarketCap platform stood at $2.25 trillion compared with $2.6 trillion at the start of December. Cryptocurrencies have benefited from easier cash conditions even in a higher inflation environment, but it was difficult to say what would happen as the Federal Reserve accelerates monetary tightening or gets ready to lift rates, said Chris Weston, head of research at brokerage Pepperstone in Melbourne. \"I feel like there would be headwinds, but as always with crypto the only thing you can have is an open mind,\" Weston said. Bargain hunters have emerged. The number of active bitcoin addresses touched 1 million after the crash, according to a report from Arcane Research, its highest since the cryptocurrency plunged 35% in May. \"Sleeping bitcoin holders seem to have been woken up by the volatility,\" Arcane analysts said. A notable dip buyer was Michael Saylor-led MicroStrategy Inc, which added 1,434 bitcoins to its holdings for about $82.4 million, the company said last week. Yet the number of bitcoin wallets holding more than 1,000 tokens fell during the week, potentially indicating profit-taking among larger players, Kraken Digital reported. Cryptocurrencies topped the list of assets expected to experience a correction in 2022, as per a survey of 500 global institutional investors conducted by Natixis Investment Managers. Another Visa survey showed 40% of global crypto owners would likely or very likely switch their primary bank to one that offers crypto-related products in the next 12 months. The Natixis survey showed that only 4 in 10 institutions considered crypto a legitimate investment option although, of the 28% already investing in crypto, 90% expect to maintain or increase their allocation in 2022.",
    timestamp: 1639642839351,
    serviceLanguage: 'ENGLISH',
    imageLinks: ['https://i-invdn-com.investing.com/trkd-images/LYNXMPEHBC0IN_L.jpg'],
    stockCodes: [
      {
        market: 'nasdaq',
        symbol: 'FB',
        freq: 1,
      },
      {
        market: 'nyse',
        symbol: 'V',
        freq: 1,
      },
      {
        market: 'nasdaq',
        symbol: 'COIN',
        freq: 1,
      },
      {
        market: 'nasdaq',
        symbol: 'COIN',
        freq: 1,
      },
      {
        market: 'nasdaq',
        symbol: 'MSTR',
        freq: 1,
      },
    ],
  },
];

export const DataStock = [
  {
    stockHistoryId: {
      symbolCode: '304100',
      marketName: 'KOSDAQ',
      baseGranularity: '15m',
      baseYyyymmdd: '20211217',
      baseDatetimelong: 1639720800,
    },
    baseYyyymmddhhmmss: '20211217150000',
    open: 14750,
    close: 14750,
    high: 14750,
    low: 14750,
    volume: 0,
    createdBy: 'system',
    createdDate: 'Dec 18, 2021, 1:51:52 AM',
    lastModifiedDate: 'Dec 18, 2021, 1:51:52 AM',
  },
  {
    stockHistoryId: {
      symbolCode: '304100',
      marketName: 'KOSDAQ',
      baseGranularity: '15m',
      baseYyyymmdd: '20211217',
      baseDatetimelong: 1639719900,
    },
    baseYyyymmddhhmmss: '20211217144500',
    open: 14850,
    close: 14800,
    high: 14850,
    low: 14750,
    volume: 2443,
    createdBy: 'system',
    createdDate: 'Dec 18, 2021, 1:51:52 AM',
    lastModifiedDate: 'Dec 18, 2021, 1:51:52 AM',
  },
  {
    stockHistoryId: {
      symbolCode: '304100',
      marketName: 'KOSDAQ',
      baseGranularity: '15m',
      baseYyyymmdd: '20211217',
      baseDatetimelong: 1639719240,
    },
    baseYyyymmddhhmmss: '20211217143400',
    open: 14800,
    close: 14800,
    high: 14800,
    low: 14800,
    volume: 0,
    createdBy: 'system',
    createdDate: 'Dec 17, 2021, 11:54:19 PM',
    lastModifiedDate: 'Dec 17, 2021, 11:54:19 PM',
  },
  {
    stockHistoryId: {
      symbolCode: '304100',
      marketName: 'KOSDAQ',
      baseGranularity: '15m',
      baseYyyymmdd: '20211217',
      baseDatetimelong: 1639719000,
    },
    baseYyyymmddhhmmss: '20211217143000',
    open: 14850,
    close: 14800,
    high: 14850,
    low: 14800,
    volume: 2952,
    createdBy: 'system',
    createdDate: 'Dec 18, 2021, 1:51:52 AM',
    lastModifiedDate: 'Dec 18, 2021, 1:51:52 AM',
  },
  {
    stockHistoryId: {
      symbolCode: '304100',
      marketName: 'KOSDAQ',
      baseGranularity: '15m',
      baseYyyymmdd: '20211217',
      baseDatetimelong: 1639718100,
    },
    baseYyyymmddhhmmss: '20211217141500',
    open: 14900,
    close: 14800,
    high: 14900,
    low: 14800,
    volume: 6160,
    createdBy: 'system',
    createdDate: 'Dec 18, 2021, 1:51:52 AM',
    lastModifiedDate: 'Dec 18, 2021, 1:51:52 AM',
  },
  {
    stockHistoryId: {
      symbolCode: '304100',
      marketName: 'KOSDAQ',
      baseGranularity: '15m',
      baseYyyymmdd: '20211217',
      baseDatetimelong: 1639717200,
    },
    baseYyyymmddhhmmss: '20211217140000',
    open: 14850,
    close: 14900,
    high: 14900,
    low: 14850,
    volume: 3107,
    createdBy: 'system',
    createdDate: 'Dec 18, 2021, 1:51:52 AM',
    lastModifiedDate: 'Dec 18, 2021, 1:51:52 AM',
  },
  {
    stockHistoryId: {
      symbolCode: '304100',
      marketName: 'KOSDAQ',
      baseGranularity: '15m',
      baseYyyymmdd: '20211217',
      baseDatetimelong: 1639716984,
    },
    baseYyyymmddhhmmss: '20211217135624',
    open: 14900,
    close: 14900,
    high: 14900,
    low: 14900,
    volume: 0,
    createdBy: 'system',
    createdDate: 'Dec 17, 2021, 11:16:47 PM',
    lastModifiedDate: 'Dec 17, 2021, 11:16:47 PM',
  },
  {
    stockHistoryId: {
      symbolCode: '304100',
      marketName: 'KOSDAQ',
      baseGranularity: '15m',
      baseYyyymmdd: '20211217',
      baseDatetimelong: 1639716300,
    },
    baseYyyymmddhhmmss: '20211217134500',
    open: 14900,
    close: 14900,
    high: 14950,
    low: 14850,
    volume: 4510,
    createdBy: 'system',
    createdDate: 'Dec 18, 2021, 1:51:52 AM',
    lastModifiedDate: 'Dec 18, 2021, 1:51:52 AM',
  },
  {
    stockHistoryId: {
      symbolCode: '304100',
      marketName: 'KOSDAQ',
      baseGranularity: '15m',
      baseYyyymmdd: '20211217',
      baseDatetimelong: 1639715474,
    },
    baseYyyymmddhhmmss: '20211217133114',
    open: 14850,
    close: 14850,
    high: 14850,
    low: 14850,
    volume: 0,
    createdBy: 'system',
    createdDate: 'Dec 17, 2021, 10:52:26 PM',
    lastModifiedDate: 'Dec 17, 2021, 10:52:26 PM',
  },
  {
    stockHistoryId: {
      symbolCode: '304100',
      marketName: 'KOSDAQ',
      baseGranularity: '15m',
      baseYyyymmdd: '20211217',
      baseDatetimelong: 1639715400,
    },
    baseYyyymmddhhmmss: '20211217133000',
    open: 14850,
    close: 14900,
    high: 14900,
    low: 14800,
    volume: 2950,
    createdBy: 'system',
    createdDate: 'Dec 18, 2021, 1:51:52 AM',
    lastModifiedDate: 'Dec 18, 2021, 1:51:52 AM',
  },
];

export const dataFeedAppend = [
  {
    collectedAt: null,
    commentId: null,
    connectomeId: 'CID_5f6a7fba-2278-4319-872c-fbcaa6f3ca57',
    content:
      "Apple iPhone development schedule delayed by China Covid lockdowns – Nikkei \n... development after China's strict COVID-19 lockdowns hampered schedule \nfor at...",
    docId: '1080817812',
    docType: null,
    esaSim: null,
    gmuseSim: null,
    id: '629166238f3a731ba78c64a5',
    imageLinks: [''],
    projectIds: null,
    publishedAt: null,
    replyId: null,
    score: null,
    serviceLanguage: null,
    serviceType: null,
    sourceId: 'https://www.chinatechnews.com/2022/05/27/66990-apple-iphone-development-schedule-delayed-by-china-covid-lockdowns-nikkei',
    sourceUri: null,
    stockCodes: null,
    timestamp: null,
    title: 'Apple iPhone development schedule delayed by China Covid ...',
    topic: null,
    topicSims: null,
    w2vSim: null,
    webSourceCategory: null,
    webSourceId: null,
  },
  {
    collectedAt: null,
    commentId: null,
    connectomeId: 'CID_5f6a7fba-2278-4319-872c-fbcaa6f3ca57',
    content:
      "Shanghai resident Yann Zhang has been searching for a way out of China for \nmonths. \"I can't see when these pandemic measures based on the \n'COVID-zero'...",
    docId: '-196988499',
    docType: null,
    esaSim: null,
    gmuseSim: null,
    id: '629166238f3a731ba78c64a6',
    imageLinks: ['data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD…AR/iswrnCgV0bgPA5v6LaTCRVaVOYVYYxncb/AAxT3CzX/9k='],
    projectIds: null,
    publishedAt: null,
    replyId: null,
    score: null,
    serviceLanguage: null,
    serviceType: null,
    sourceId: 'https://www.abc.net.au/news/2022-05-28/china-shanghai-covid-zero-policy-pushes-young-people-to-leave/101099696',
    sourceUri: null,
    stockCodes: null,
    timestamp: null,
    title: 'As COVID-19 lockdowns continue, more young people are ...',
    topic: null,
    topicSims: null,
    w2vSim: null,
    webSourceCategory: null,
    webSourceId: null,
  },
  {
    collectedAt: null,
    commentId: null,
    connectomeId: 'CID_5f6a7fba-2278-4319-872c-fbcaa6f3ca57',
    content:
      "... this year weren't “synchronized,” namely, the war in Ukraine, \nsupply-chain issues, China's COVID-19 lockdowns, and central bank interest \nrate increases.",
    docId: '1403761441',
    docType: null,
    esaSim: null,
    gmuseSim: null,
    id: '629166238f3a731ba78c64a7',
    imageLinks: ['data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD…etpok7bbCvH23xnY0jo7HGOWZXhoEsKeV9Tiyo0p9lLo//9k='],
    projectIds: null,
    publishedAt: null,
    replyId: null,
    score: null,
    serviceLanguage: null,
    serviceType: null,
    sourceId: 'https://fortune.com/2022/05/27/recession-prediction-bank-of-america-says-extended-weakness-more-likely/',
    sourceUri: null,
    stockCodes: null,
    timestamp: null,
    title: "Recession is not likely, 'extended weakness' instead: Bank of ...",
    topic: null,
    topicSims: null,
    w2vSim: null,
    webSourceCategory: null,
    webSourceId: null,
  },
];
