spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8088"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    baseUrl: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0
