spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://13.21.34.201:8088"
  rabbitmq:
    host: 13.21.34.201
    port: 5672
    username: guest
    password: guest
  zipkin:
    baseUrl: http://13.21.34.201:9411
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    ROOT: INFO
    com.saltlux.deepsignal: INFO
