spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://192.168.10.16:8088"
  rabbitmq:
    host: 192.168.10.12
    port: 5672
    username: deepsignal
    password: deeppass22
  zipkin:
    baseUrl: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0
