spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:8088"
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
