spring:
  application:
    name: discovery-service
  config:
    import: "optional:configserver:http://localhost:8088"
  rabbitmq:
    host: 13.21.34.201
    port: 5672
    username: guest
    password: guest
logging:
  level:
    ROOT: INFO
    com.saltlux.deepsignal: INFO
