spring:
  application:
    name: discovery-service
  config:
    import: "optional:configserver:http://192.168.10.16:8088"
  rabbitmq:
    host: 192.168.10.12
    port: 5672
    username: deepsignal
    password: deeppass22
logging:
  level:
    ROOT: INFO
    com.saltlux.deepsignal: INFO
