server:
  port: 8088
spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/deepsignalai/deepsignal-cloud-config.git
          username: deepsignalai
          password: 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
          default-label: main
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
